<script>
    let letter = {
        format: 'Letter',
        base: 'Vintage',
        min: 60,
        max: null,
        copies: 4,
        formatRules: [
            "All cards must be Vintage Legal",
            "Letters are chosen randomly by die (d20) roll by impartial party (Mike)",
            "All cards must start with chosen letter, basic lands ignore this rule",
            "Cards starting with The followed by a word are also allowed. example: Chosen letter of R can use The Rack in their deck",
            "Deck can only contain 4 cards with goblin creature type total, regardless of letter; example: (4 Krenko, Mob Boss in a K deck)",
        ],
        samsBans:[
            "Stoneforge Mystic",
            "Timevault"
        ],
        bans: [
            "Adriana's Valor",
            "Advantageous Proclamation",
            "Aerialephant",
            "Ambassador Blorpityblorpboop",
            "Amulet of Quoz",
            "Assemble the Rank and Vile",
            "Backup Plan",
            "Baaallerina",
            "_____ Balls of Fire",
            "Bioluminary",
            "_____ Bird Gets the Worm",
            "Brago's Favor",
            "Bronze Tablet",
            "Carnival Carnivore",
            "Chaos Orb",
            "Chicken Troupe",
            "Clandestine Chameleon",
            "Cleanse",
            "Coming Attraction",
            "Command Performance",
            "Contract from Below",
            "Crusade",
            "Darkpact",
            "Deadbeat Attendant",
            "Dee Kay, Finder of the Lost",
            "Discourtesy Clerk",,
            "Demonic Attorney",
            "Double Stroke",
            "Done for the Day",
            "Draconian Gate-Bot",
            "Echoing Boon",
            "Emissary's Ploy",
            "Falling Start",
            "Fight the _____ Fight",
            "Finishing Move",
            "Glitterflitter",
            "_____ Goblin",
            "Hired Heist",
            "Hold the Perimeter",
            "Hymn of the Wilds",
            "Immediate Action",
            "Imprison",
            "Incendiary Dissent",
            "Invoke Prejudice",
            "Iterative Analysis",,
            "Jeweled Bird",
            "Jihad",
            "Last Voyage of the _____",
            '"Lifetime" Pass Holder',
            "Line Cutter",
            "Lineprancers",
            "Marchesa's Surprise Party",
            "Make a _____ Splash",
            "Minotaur de Force",
            "Monitor Monitor",
            "Muzzio's Preparations",
            "Myra the Magnificent",
            "Natural Unity",
            "_____-o-saurus",
            "Park Bleater",
            "Petting Zookeeper",
            "Pin Collection",
            "Power Play",
            "Pradesh Gypsies",
            "Prize Wall",
            "Proficient Pyrodancer",
            "Rebirth",
            "Robo-Piñata",
            "_____ _____ Rocketship",
            "Roxi, Publicist to the Stars",
            "Rule with an Even Hand",
            "Quick Fixer",
            "Rad Rascal",
            "Ride Guide",
            "Scampire",
            "Seasoned Buttoneer",
            "Secret Summoning",
            "Secrets of Paradise",
            "Shahrazad",
            "Soul Swindler",
            "Sovereign's Realm",
            "Spinnerette, Arachnobat",
            "Squirrel Squatters",
            "Step Right Up",
            "Stiltstrider",
            "Stone-Throwing Devils",
            "Summoner's Bond",
            "Sword-Swallowing Seraph",
            "Tempest Efreet",
            "Timmerian Fiends",
            "Ticketomaton",
            "_____ _____ _____ Trespasser",
            "The Most Dangerous Gamer",
            "Tusk and Whiskers",
            "Unexpected Potential",
            "Weight Advantage",
            "Wicker Picker",
            "Wizards of the _____",
            "Wolf in _____ Clothing",
            "Worldknit"
        ],
        restricted: [
            "Ancestral Recall",
            "Balance",
            "Black Lotus",
            "Brainstorm",
            "Chalice of the Void",
            "Channel",
            "Demonic Consultation",
            "Demonic Tutor",
            "Dig Through Time",
            "Flash",
            "Gitaxian Probe",
            "Golgari Grave-Troll",
            "Gush",
            "Imperial Seal",
            "Karn, the Great Creator",
            "Library of Alexandria",
            "Lion's Eye Diamond",
            "Lodestone Golem",
            "Lotus Petal",
            "Mana Crypt",
            "Mana Vault",
            "Memory Jar",
            "Mental Misstep",
            "Merchant Scroll",
            "Mind's Desire",
            "Monastery Mentor",
            "Mox Emerald",
            "Mox Jet",
            "Mox Pearl",
            "Mox Ruby",
            "Mox Sapphire",
            "Mystic Forge",
            "Mystical Tutor",
            "Narset, Parter of Veils",
            "Necropotence",
            "Sol Ring",
            "Strip Mine",
            "Thorn of Amethyst",
            "Time Vault",
            "Time Walk",
            "Timetwister",
            "Tinker",
            "Tolarian Academy",
            "Treasure Cruise",
            "Trinisphere",
            "Urza's Saga",
            "Vampiric Tutor",
            "Vexing Bauble",
            "Wheel of Fortune",
            "Windfall",
            "Yawgmoth's Will",
        ],
        clarifications: [
            "Using a 60 card deck as an example, you can have 56 cards without and 4 cards with goblin type."
        ],
    }

    let sams = {
        format: 'Standard',
        base: 'Standard',
        min: 60,
        max: null,
        copies: 4,
        formatRules: [
            "All cards must be Standard Legal",
        ],
        samsBans:[],
        bans: [],
        restricted: [],
        clarifications: [],
    }

    let choice = {
        format: 'Two-Type Modern',
        base: 'Modern',
        min: 60,
        max: null,
        copies: 4,
        formatRules: [
            "All cards must be Modern Legal",
            "Choose two Card types from this list; Artifact, Battle, Creature, Enchantment, Instant, Kindred, Nonbasic Land, Planeswalker, Sorcery, Tribal",
            'A deck can only consist of cards containing these and only these types in their "type line", Basic Lands Ignore this rule',
        ],
        samsBans:[],
        bans: [
            "Ancient Den",
            "Arcum's Astrolabe",
            "Birthing Pod",
            "Blazing Shoal",
            "Bridge From Below",
            "Chrome Mox",
            "Cloudpost",
            "Dark Depths",
            "Deathrite Shaman",
            "Dig Through Time",
            "Dread Return",
            "Eye of Ugin",
            "Faithless Looting",
            "Field of the Dead",
            "Fury",
            "Gitaxian Probe",
            "Glimpse of Nature",
            "Golgari Grave-Troll",
            "Great Furnace",
            "Green Sun's Zenith",
            "Grief",
            "Hogaak, Arisen Necropolis",
            "Hypergenesis",
            "Krark-Clan Ironworks",
            "Lurrus of the Dream-Den",
            "Mental Misstep",
            "Mox Opal",
            "Mycosynth Lattice",
            "Mystic Sanctuary",
            "Nadu, Winged Wisdom",
            "Oko, Thief of Crowns",
            "Once Upon a Time",
            "Ponder",
            "Punishing Fire",
            "Rite of Flame",
            "Seat of the Synod",
            "Second Sunrise",
            "Seething Song",
            "Sensei's Divining Top",
            "Simian Spirit Guide",
            "Skullclamp",
            "Splinter Twin",
            "Summer Bloom",
            "Tibalt's Trickery",
            "Treasure Cruise",
            "Tree of Tales",
            "Umezawa's Jitte",
            "Up the Beanstalk",
            "Uro, Titan of Nature's Wrath",
            "Vault of Whispers",
            "Violent Outburst",
            "Yorion, Sky Nomad"
        ],
        restricted: [],
        clarifications: [
            "305.8. Any land with the supertype “basic” is a basic land. Any land that doesn’t have this supertype is a nonbasic land, even if it has a basic land type.",
            "A card can have one or both of the types but cannot have another type not chosen, example Artifact/Planeswalker cannot have the card Simulacrum, which is an Artifact Creature, in their deck",
        ],
    }
</script>

<h1>Sam's Annual Tournament</h1>
